config/routes.rb
SmallCommunities::Application.routes.draw do
  
  devise_for :users
  resources :users
  match "/members" => "users#index"
  
  resources :events do
    member do
      get 'calendar'
      get 'soldout'
      get 'tix_atdoor'
      post 'rsvp'
      get  :rsvps
    end
  end
  controller :events do
    match "/past_events" => :past
    match "upcoming_events" => :upcoming
  end
  
  resources :stat_pages
  controller :stat_pages do
    match '/about' => :about, :as => 'about'
    match '/contact' => :contact, :as => 'contact'
    match '/memberships' => :memberships, :as => 'memberships'
  end
  
  controller :speakers do
    match '/past_speakers' => :past_speakers
  end
  
  root :to => "events#index"

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :presentations
  has_many :speakers, through: :presentations
  has_many :rsvps
  has_many :users, through: :rsvps
  has_and_belongs_to_many :paypals

  EVT_ACTIVE_STATUSES = %w(on_sale at_door)
  EVT_INACTIVE_STATUSES = %w(sold_out past)
  
  validates :title, presence: true
  validates :occurs_on, presence: true
  validates :status, inclusion: {in: EVT_ACTIVE_STATUSES + EVT_INACTIVE_STATUSES}
  validates :page_template, presence: true
  
  attr_accessible :title, :subtitle, :occurs_on, :description, :page_template

  class << self
    def future_events
      where("occurs_on > ?", Date.current).order("occurs_on DESC")
    end

    def past_events
      where("occurs_on < ?", Date.current).order("occurs_on DESC")
    end

    def current_year
      where(:occurs_on => Date.current.beginning_of_year..Date.current.end_of_year).order(:occurs_on)
    end

    def current
      where("occurs_on > ?", Date.current).order(:occurs_on).limit(1)
    end

    def current_event
      Event.current.first
    end

    # TODO This needs to calculate the next logical date from Date.current, not the next logical date after the last event in the DB
    def tba
      last_event = Event.where("occurs_on < ?", Date.current).limit(1).order("occurs_on DESC").first
      last_plus_one = self.next_event(last_event.present? ? last_event.occurs_on : Date.current.beginning_of_month)
      # 'To Be Announced', 'Date is tentative until program is confirmed.'
      Event.new({title: Setting.retrieve('default_event_title'), page_template: 'event', occurs_on: last_plus_one, description: Setting.retrieve('default_event_description')})
    end

    def next_event last_date
      # defaults to second Tuesday of the next month
      nm = last_date.next_week(self.default_meeting_day)
      until valid_next_event_date(nm)
        nm = nm.next_week(self.default_meeting_day)
      end
      nm
    end

    def valid_next_event_date nxdt
      dmw = self.default_meeting_week
      stdt = dmw*7 || 1
      eddt = stdt + 7
      nxdt >= Date.current and ((nxdt.day > stdt) and (nxdt.day < eddt))
    end

    def default_meeting_day
      # 'w:2,d:tuesday'
      Setting.find_by_name("default_next_event_date").value.split(",").last.split(":").last.to_sym
    end

    def default_meeting_week
      # 'w:2,d:tuesday'
      Setting.find_by_name("default_next_event_date").value.split(",").first.split(":").last.to_i - 1
    end
  end
  
  def is_current?
    Event.current_event.present? ? Event.current_event == self : false
  end
  
  def change_status(new_status)
    status = new_status
    save!
  end
  
  def active?
    EVT_ACTIVE_STATUSES.include? status
  end
  
  def on_sale?
    status == 'on_sale'
  end
  
  def soldout?
    status == 'sold_out'
  end
  
  def at_door?
    status == 'at_door'
  end
  
  def special_paypal
    self.paypals.where(button_type: 'special').first || nil
  end
  
  def regular_paypal
    self.paypals.where(button_type: 'regular').first || nil
  end
  
  def to_ics
    event = Icalendar::Event.new
    event.start = occurs_on.strftime("%Y%m%dT%H%M%S")
    event.end = (occurs_on + int_Setting.retrieve('event_length').minutes).strftime("%Y%m%dT%H%M%S")
    event.summary = Setting.retrieve('short_name') + ': ' + title
    spkrs = speakers.collect {|s| s.name}
    spkrs = speakers.present? ? "Speakers: " + spkrs.join(", ") : ""
    event.description = self.description.gsub(/<br\/>/, '\n') + '\n\n' + spkrs
    event.url = Setting.retrieve('corp_url')
    event.location = location
    event.klass = "PUBLIC"
    event.created = created_at
    event.last_modified = updated_at
    event
  end
  
  def check_status
    change_status('past') if occurs_on < Date.current and status != 'past'
  end
  
  # for RailsAdmin dropdown
  def status_enum
    %w(on_sale at_door sold_out past)
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :only => [:rsvp]
  before_filter :setup, :only => [:index, :show, :calendar]
  
  def index
  end

  def past
    @events = Event.past_events
  end

  def upcoming
    @events = Event.current_year
    if @events.blank?
      flash.notice = "There are no upcoming events scheduled"
      redirect_to :back
    end
  end

  def show
  end

  def soldout
    @event = Event.find(params[:id])
    @event.change_status("sold_out") if @event.active?
    redirect_to event_path(@event)
  end
  
  def at_door
    @event = Event.find(params[:id])
    @event.change_status("at_door") if @event.active?
    redirect_to event_path(@event)
  end
  
  def calendar
    respond_to do |format|
      format.ics {
        calendar = Icalendar::Calendar.new
        calendar.custom_property("X-WR-CALNAME;VALUE=TEXT", Setting.retrieve("short_name")+@event.occurs_on.to_s(:month_year))
        calendar.add_event(@event.to_ics)
        calendar.publish
        send_data(calendar.to_ical, :type => 'text/calendar', :filename => 'sc_cal_' + params[:id])
      }
    end
  end
  
  def rsvp
    if params[:id].present?
      evt = Event.find(params[:id])
      Rsvp.create!({:event => evt, :user => current_user})
      render :update do |page|
        page.replace 'memberRSVP', t(:thanks_for_rsvp)
      end
    end
  end
  
  def rsvps
    @event = Event.find(params[:id])
    unless @rsvps = @event.rsvps
      redirect_to :back
    end
  end
  
  protected
  def setup
    @event = params[:id].blank? ? Event.current_event : Event.find(params[:id])
    # if no specific event requested and no next event in dba,
    # fabricate one for this request
    @event ||= Event.tba
    # checks if Event should be moved to 'past' status
    @event.check_status
    @context_title = @event.title
    @show_rsvp = user_signed_in? and current_user.rsvps.present? and current_user.rsvps.where(:event_id => @event.id).blank?
    @sponsors = User.current_sponsors if @event.show_sponsors
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def location_label event
    if event.location.blank?
      l_url = Setting.retrieve 'default_location_url'
      l_label = Setting.retrieve 'default_location_label'
      link_to l_label, l_url
    else
      event.location
    end
  end
  
  def event_pricing event
    if event.special_pricing.present?
      t(:special_pricing) + event.special_pricing
    else
			t(:advance_pricing) + Setting.retrieve('regular_event_advance') + "<br/>" + t(:door_pricing) + Setting.retrieve('regular_event_door')
    end
  end
  
  def event_speakers_list speakers, needs_with=true
    spkrs = []
    speakers.each do |speaker|
      if speaker.url == ''
        spkrs << speaker.name
      else
		    spkrs << link_to(speaker.name, speaker.url)
	    end
	  end if speakers.present?
	  wth = speakers.present? ? needs_with ? t(:with) + ' ' : t(:with) + ' ' : ''
	  raw(wth + spkrs.to_sentence)
  end
  
  def show_year curyear, evt_year
    curyear != evt_year ? content_tag(:div, content_tag(:div, curyear), :class => 'curyear') : ''
  end
  
  def short_desc_link event
    spkrs = event_speakers_list(event[:speakers], false) unless event[:speakers] == ''
    link_to(event[:title], event[:url]) + ' ' + spkrs
  end
  
  def time_string event
    raw event.occurs_on.to_s(:basic) + ", " + Setting.retrieve('default_event_start_time') + " "
  end
end

app/views/events/_event.html.haml
#event-header
	#current-text= @event.is_current? ? t(:next_meeting_label) : ''
	#msgHolder
	%h2#event-title= raw @event.title
	#speaker-names= event_speakers_list(@event.speakers) if @event.speakers.present?
	#event-infobox= render :partial => 'infobox'
#meeting-description= raw @event.description
= render(:partial => 'speakers', :speakers => @event.speakers) if @event.speakers.present?

app/views/events/_event_admin_buttons.haml
= link_to( t(:see_rsvps), rsvps_event_path(@event), :id => 'evt-attendees', :class => 'button-like', :title => t(:event_rsvps_button) ) if @event.rsvps.present?
= link_to( t(:mark_soldout), soldout_event_path(@event), :id => 'evt-soldout', :class => 'button-like' ) if @event.active?
= link_to( t(:mark_atdoor), tix_atdoor_event_path(@event), :id => 'evt-atdoor', :class => 'button-like' ) if @event.on_sale?

app/views/events/_future_event.html.haml
.event.list_row{:class => cycle('list_odd', 'list_even')}
	.event-date.list_label= future_event[:occurs_on].to_s(:month_day)
	.list_detail= short_desc_link(future_event)

app/views/events/_infobox.html.haml
#event-infobox-inner
	= special_event_date(@event) 
	.strong.big
		= time_string @event
	.location= location_label(@event)
	= render :partial => 'events/share_event'
	- if @event.is_current?
		= render :partial => 'rsvp_block'
		= render :partial => 'event_admin_buttons' if (user_signed_in? and current_user.admin?)

app/views/events/_past_event.html.haml
- curyear = events.first.occurs_on.year
= show_year(curyear, curyear+1)
- events.each do |ev|
	- curyear = ev.occurs_on.year
	- last_month = ev.occurs_on.month == 1 ? 'last' : ''
	.event.list_row{:class => last_month + ' ' + cycle('list_odd', 'list_even')}
		.event-date.list_label= ev.occurs_on.to_s(:month_day)
		.list_detail= link_to raw(ev.title), event_path(ev)
		.list_detail= event_speakers_list(ev.speakers, false)
	= show_year(curyear -1, ev.occurs_on.year) if ev.occurs_on.month == 1

app/views/events/_ppl_block.html.haml
- if @event.regular_paypal && !current_member
	.rsvpdiv
		= render :partial => 'ppl_button', :locals => {:ppl_code => @event.regular_paypal, :ppl_label => t(:guest), :ppl_pricing => event_pricing(@event)}
		- if @event.special_paypal
			= render :partial => 'ppl_button', :locals => {:ppl_code => @event.special_paypal, :ppl_label => t(:student_senior), :ppl_pricing => t(:advance_door)+": " + Setting.retrieve('special_event')}

app/views/events/_rsvp_block.html.haml
- if @show_rsvp and @event.id.present?
	#memberRSVP
		= link_to t(:member_rsvp_label), rsvp_event_path(:id => @event.id), :method => :post, :remote => true, :class => 'button-like'

app/views/events/_share_event.html.haml
#social-shares
	= link_to(image_tag('icons/calendar_day.png', :style => 'height: 25px;', :title => 'Add to Calendar', :alt => 'Add to Calendar'), {:action => :calendar, :id => @event.id, :protocol => "webcal", :format => :ics, :only_path => false}, :class => 'calLink') if @event.is_current?
	= link_to t(:tweet), "http://twitter.com/share", :remote => true, :data_count => "none", :data_via => Setting.retrieve("twitter_account"), :class => "twitter-share-button"
	%script{ :type => "text/javascript", :src => "//platform.twitter.com/widgets.js" }
	%iframe{:src => "http://www.facebook.com/plugins/like.php?href=#{request.url}&amp;layout=button_count&amp;show_faces=false&amp;width=200&amp;action=like&amp;font=verdana&amp;colorscheme=light&amp;height=25", :scrolling => "no", :frameborder => "0", :style => "border:none; overflow:hidden; width:300px; height:25px;", :allowTransparency => "true"}

app/views/events/_speakers.html.haml
#speaker-description
	%h3= t(:about_speakers_title) + (speakers.size == 1 ? "" : "Speaker".pluralize)
	- speakers.each do |s|
		.speaker
			%span.speaker-image= image_tag s.image_url, :alt => s.name
			.speaker-bio
				%span.strong= s.name
				= raw s.bio

app/views/events/index.html.haml
= render :partial => @event.page_template

app/views/events/past.html.haml
#past-events
	%h2= t(:past_events_title)
	.gen_page
		- if @events.present?
			= render :partial => "past_event", :events => @events
		- else
			%div= "No past events yet"

app/views/events/rsvps.html.haml
%h2= t(:rsvp).pluralize + ": " + @event.title

%div
	= t(:rsvp) + " " + t(:count) + ":"
	= @rsvps.count

- idx = 0
- @rsvps.each do |rsvp|
	- idx = idx + 1
	%div{:class => cycle('list_odd', 'list_even')}= link_to idx.to_s + ' ' + rsvp.user.name, rsvp.user

app/views/events/show.html.haml
= render :partial => @event.page_template

app/views/events/upcoming.html.haml
#future-events
	%h2= raw(Setting.retrieve('current_year') + " &#x2721; " + t(:schedule))
	%p= t(:standard_meeting_explainer)
	= render :partial => "future_event", :collection => @events