config/routes.rb
SmallCommunities::Application.routes.draw do
  
  devise_for :users
  resources :users
  match "/members" => "users#index"
  
  resources :events do
    member do
      get 'calendar'
      get 'soldout'
      get 'tix_atdoor'
      post 'rsvp'
      get  :rsvps
    end
  end
  controller :events do
    match "/past_events" => :past
    match "upcoming_events" => :upcoming
  end
  
  resources :stat_pages
  controller :stat_pages do
    match '/about' => :about, :as => 'about'
    match '/contact' => :contact, :as => 'contact'
    match '/memberships' => :memberships, :as => 'memberships'
  end
  
  controller :speakers do
    match '/past_speakers' => :past_speakers
  end
  
  root :to => "events#index"

end

app/views/layouts/_banner.html.haml
#banner
	#banner-img= link_to logo_image('sc-logo-200px.png', Setting.retrieve('short_name') + '!'), root_url
	%h1#org_title= link_to(Setting.retrieve('long_name'), root_url)
	#login-block= signin_link + '	' + link_to(t(:contact_link), contact_path)
	- if Setting.retrieve('tag_line')
		%h2#tagline= Setting.retrieve('tag_line')

app/views/layouts/_footer.html.haml
#footer
	= raw t(:copyright) + " &copy; "
	= Setting.retrieve('copyright') + Setting.retrieve('current_year') + ',' 
	= Setting.retrieve('corp_name')
	%br
	= link_to t(:contact_link), contact_url

app/views/layouts/_js.html.haml
= javascript_include_tag :defaults
= javascript_include_tag 'apprise-1.5.min', 'jquery.superfish', "http://platform.twitter.com/anywhere.js?id=APIKey&v=1"

:javascript
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', '#{Setting.retrieve("google-analytics")}']);
	_gaq.push(['_setDomainName', 'none']);
	_gaq.push(['_trackPageview']);
	(function() {
		var ga = document.createElement('script');
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		ga.setAttribute('async', 'true');
		document.documentElement.firstChild.appendChild(ga);
	})();

app/views/layouts/_photo_block.html.haml
.photoblock
	- photos.each do |photo|
		= image_tag photo.filename, :alt => photo.caption, :title => photo.caption

app/views/layouts/_ppl_button.html.haml
/ expects in locals: ppl_code, ppl_label, ppl_pricing

= form_tag "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id="+ppl_code, :id => idify(ppl_label)+"PPL", :class => 'ppButton' do
	.extra-bottom
		= hidden_field_tag :name => "cmd", :value => "_s-xclick"
		= hidden_field_tag :name => "hosted_button_id", :value => ppl_code
		= label_tag (idify(ppl_label)+"MtgBtn").to_sym, ppl_label, :title => tip
	.div
		= image_submit_tag "https://www.paypal.com/en_US/i/btn/btn_paynow_SM.gif", :style => "border: none;", :alt => "PayPal - The safer, easier way to pay online!", :id => idify(ppl_label)+"MtgBtn"
		= image_tag "https://www.paypal.com/en_US/i/scr/pixel.gif", :style => "border: none;", :width => "1", :height => "1"
	= raw ppl_pricing

app/views/layouts/_sidebar.html.haml
= render :partial => "layouts/social_links" if @socnet_links.present?
= render :partial => "layouts/twitter" if Setting.retrieve('twitter_account').present?

app/views/layouts/_social_links.html.haml
#socnet_links
	%h2= t(:socnet_links_title)
	%ul#soc-networks
		- @socnet_links.each do |sl|
			%li{:class => sl[:label].split("_").first.downcase}= link_to(t(sl[:label].to_sym), sl[:url])

app/views/layouts/_twitter.html.haml
#tweets-anywhere-container
	%h2= raw t(:latest_news) + ' ' + link_to(image_tag("http://twitter-badges.s3.amazonaws.com/t_small-a.png", :alt => t(:follow) + " "+ Setting.retrieve('twitter_account') + " on Twitter"), "http://www.twitter.com/"+Setting.retrieve('twitter_account'))
	#tweets-anywhere

app/views/layouts/application.html.haml
!!! 5
%html
	%head
		%title= page_title(@context_title)
		= raw stylesheet_link_tag('jquery.jtweetsanywhere-1.2.1', 'screen', 'apprise.min', :media => 'screen, projection')
		= raw stylesheet_link_tag('superfish', :media => 'screen, projection')
		= raw stylesheet_link_tag('print', :media => 'print')
		/[if lt IE 8]
			= raw stylesheet_link_tag('ie', :media => 'screen, projection')
		/ UNCOMMENT for CSS debug stylesheet
		/ ALSO uncomment body class
		/ = raw stylesheet_link_tag 'holmes'
		= favicon_link_tag
		/ Need the following block to pull in the appropriate Twitter account from Settings
		:erb
			<script>
				var scTwitterAccount = "<%= Setting.retrieve('twitter_account') %>"
			</script>
		= csrf_meta_tag
	/ %body.holmes-debug
	%body
		#container
			%header
				= render :partial => 'layouts/banner'
				%nav= render_navigation :items => @menu, :expand_all => false
			%section#content_container
				%sidebar= render :partial => 'layouts/sidebar'
				%section#content
					- if flash.present?
						#flash
							- flash.each do |key, value|
								%div{:id => ["flash", key]}= value
					%section#content-inner= yield
			%section#sponsorBlock= render :partial => 'layouts/sponsors_block' if @show_sponsors
			/ = render(:partial => 'users/sponsors', :sponsors => @sponsors) if @sponsors.present?
			%footer= render :partial => 'layouts/footer'
		/ bottom-loading JavaScript
		= render :partial => 'layouts/js'